export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>Place your introduction and profile here.</p>\n","readingTime":{"minutes":0.04,"words":13},"title":"Intro Page","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"主页","icon":"house"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"category":["Guide"],"tag":["disable"],"excerpt":"<p>You can disable some function and layout on the page by setting the Frontmatter of the page.</p>\n","readingTime":{"minutes":0.28,"words":83},"title":"Disabling layout and features","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"category":["Guide"],"tag":["encryption"],"isEncrypted":true,"readingTime":{"minutes":0.3,"words":90},"title":"Encryption Article","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"category":["Guide"],"tag":["Layout"],"excerpt":"<p>The layout contains:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">Navbar</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">Sidebar</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">Footer</a></li>\n</ul>","readingTime":{"minutes":0.35,"words":106},"title":"Layout","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"category":["Guide"],"tag":["Markdown"],"excerpt":"<p>VuePress basically generate pages from Markdown files. So you can use it to generate documentation or blog sites easily.</p>\n<p>You should create and write Markdown files, so that VuePress can convert them to different pages according to file structure.</p>\n","readingTime":{"minutes":2.33,"words":699},"title":"Markdown Enhance","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"author":"Ms.Hope","date":1577836800000,"category":["Guide"],"tag":["Page config","Guide"],"sticky":true,"excerpt":"<p>Content before <code>more</code> comment is regarded as page excerpt.</p>\n","readingTime":{"minutes":1.14,"words":341},"title":"Page Config","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"category":["Guide"],"readingTime":{"minutes":0.04,"words":12},"title":"Features demo","icon":"laptop-code","type":"article"} }],
  ["/posts/cherry.html", { loader: () => import(/* webpackChunkName: "posts_cherry.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/cherry.html.js"), meta: {"date":1641686400000,"category":["Cherry"],"tag":["red","small","round"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.09,"words":27},"title":"Cherry","icon":"pen-to-square","type":"article"} }],
  ["/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "posts_dragonfruit.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/dragonfruit.html.js"), meta: {"date":1641772800000,"category":["Dragon Fruit","Fruit"],"tag":["red","big"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.1,"words":29},"title":"Dragon Fruit","icon":"pen-to-square","type":"article"} }],
  ["/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "posts_strawberry.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/strawberry.html.js"), meta: {"date":1641859200000,"category":["Fruit","Strawberry"],"tag":["red","small"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.09,"words":27},"title":"Strawberry","icon":"pen-to-square","type":"article"} }],
  ["/posts/tomato.html", { loader: () => import(/* webpackChunkName: "posts_tomato.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/tomato.html.js"), meta: {"date":1641945600000,"category":["Vegetable"],"tag":["red","round"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.11,"words":32},"title":"Tomato","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "posts_apple_1.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/apple/1.html.js"), meta: {"date":1640995200000,"category":["Apple"],"tag":["red","big","round"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.09,"words":28},"title":"Apple 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "posts_apple_2.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/apple/2.html.js"), meta: {"date":1641081600000,"category":["Apple"],"tag":["red","big","round"],"excerpt":"\n<p>A apple article being stared.</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"Apple 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "posts_apple_3.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/apple/3.html.js"), meta: {"date":1641168000000,"category":["Apple","Fruit"],"tag":["red","big","round"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.1,"words":29},"title":"Apple 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "posts_apple_4.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/apple/4.html.js"), meta: {"date":1641254400000,"category":["Apple","Fruit"],"tag":["red","big","round"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.1,"words":29},"title":"Apple 4","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "posts_banana_1.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/banana/1.html.js"), meta: {"date":1641340800000,"category":["Banana","Fruit"],"tag":["yellow","curly","long"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.1,"words":29},"title":"Banana 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "posts_banana_2.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/banana/2.html.js"), meta: {"date":1641427200000,"category":["Banana","Fruit"],"tag":["yellow","curly","long"],"excerpt":"\n<p>A banana article being stared with number <code>10</code>.</p>\n","readingTime":{"minutes":0.14,"words":41},"title":"Banana 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "posts_banana_3.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/banana/3.html.js"), meta: {"date":1641513600000,"category":["Banana"],"tag":["yellow","curly","long"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.09,"words":28},"title":"Banana 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "posts_banana_4.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/banana/4.html.js"), meta: {"date":1641600000000,"category":["Banana"],"tag":["yellow","curly","long"],"excerpt":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","readingTime":{"minutes":0.09,"words":28},"title":"Banana 4","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/posts/apple/", { loader: () => import(/* webpackChunkName: "posts_apple_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/apple/index.html.js"), meta: {"title":"Apple"} }],
  ["/posts/banana/", { loader: () => import(/* webpackChunkName: "posts_banana_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/posts/banana/index.html.js"), meta: {"title":"Banana"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/guide/", { loader: () => import(/* webpackChunkName: "category_guide_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/guide/index.html.js"), meta: {"title":"Guide 分类","index":false} }],
  ["/category/cherry/", { loader: () => import(/* webpackChunkName: "category_cherry_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/cherry/index.html.js"), meta: {"title":"Cherry 分类","index":false} }],
  ["/category/dragon-fruit/", { loader: () => import(/* webpackChunkName: "category_dragon-fruit_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/dragon-fruit/index.html.js"), meta: {"title":"Dragon Fruit 分类","index":false} }],
  ["/category/fruit/", { loader: () => import(/* webpackChunkName: "category_fruit_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/fruit/index.html.js"), meta: {"title":"Fruit 分类","index":false} }],
  ["/category/strawberry/", { loader: () => import(/* webpackChunkName: "category_strawberry_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/strawberry/index.html.js"), meta: {"title":"Strawberry 分类","index":false} }],
  ["/category/vegetable/", { loader: () => import(/* webpackChunkName: "category_vegetable_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/vegetable/index.html.js"), meta: {"title":"Vegetable 分类","index":false} }],
  ["/category/apple/", { loader: () => import(/* webpackChunkName: "category_apple_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/apple/index.html.js"), meta: {"title":"Apple 分类","index":false} }],
  ["/category/banana/", { loader: () => import(/* webpackChunkName: "category_banana_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/category/banana/index.html.js"), meta: {"title":"Banana 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/disable/", { loader: () => import(/* webpackChunkName: "tag_disable_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/disable/index.html.js"), meta: {"title":"标签: disable","index":false} }],
  ["/tag/encryption/", { loader: () => import(/* webpackChunkName: "tag_encryption_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/encryption/index.html.js"), meta: {"title":"标签: encryption","index":false} }],
  ["/tag/layout/", { loader: () => import(/* webpackChunkName: "tag_layout_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/layout/index.html.js"), meta: {"title":"标签: Layout","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/page-config/", { loader: () => import(/* webpackChunkName: "tag_page-config_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/page-config/index.html.js"), meta: {"title":"标签: Page config","index":false} }],
  ["/tag/guide/", { loader: () => import(/* webpackChunkName: "tag_guide_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/guide/index.html.js"), meta: {"title":"标签: Guide","index":false} }],
  ["/tag/red/", { loader: () => import(/* webpackChunkName: "tag_red_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/red/index.html.js"), meta: {"title":"标签: red","index":false} }],
  ["/tag/small/", { loader: () => import(/* webpackChunkName: "tag_small_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/small/index.html.js"), meta: {"title":"标签: small","index":false} }],
  ["/tag/round/", { loader: () => import(/* webpackChunkName: "tag_round_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/round/index.html.js"), meta: {"title":"标签: round","index":false} }],
  ["/tag/big/", { loader: () => import(/* webpackChunkName: "tag_big_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/big/index.html.js"), meta: {"title":"标签: big","index":false} }],
  ["/tag/yellow/", { loader: () => import(/* webpackChunkName: "tag_yellow_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/yellow/index.html.js"), meta: {"title":"标签: yellow","index":false} }],
  ["/tag/curly/", { loader: () => import(/* webpackChunkName: "tag_curly_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/curly/index.html.js"), meta: {"title":"标签: curly","index":false} }],
  ["/tag/long/", { loader: () => import(/* webpackChunkName: "tag_long_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/tag/long/index.html.js"), meta: {"title":"标签: long","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"E:/leetcode-notes/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
